### ISSUE TITLE
Can you remove the LinkedList class from the queue?

### ISSUE THREAD

**Issue by oriasm** [bdourdoufis/cs4500assignment1part2#10]
Can you remove the LinkedList pointer in the Queue class? We'd like to be able to implement the queue in our own way. Perhaps using an existing version of a linked list so it would be nice to import that and use it freely.

**Comment by Nomenokes** [comment]
Agreed, looks like none of the tests or external Queue methods depend on it so it would be better to leave out

**Comment by mwaldrich** [comment]
sure, done
