### ISSUE TITLE
Updating Object and String specs

### ISSUE THREAD

**Issue by chasebish** [bdourdoufis/cs4500assignment1part2#12]
Is it possible you can update your object.h and string.h files to mirror the [repository](https://github.com/chasebish/cwc_object_string) found on this [Piazza post](https://piazza.com/class/k51bluky59n2jr?cid=345)? If all groups implement the same Object and String APIs everybody would benefit.

**Comment by chasebish** [comment]
I can also create a pull request if that's easier for you guys

**Comment by mwaldrich** [comment]
fixed
