### ISSUE TITLE
cleaning memeory in the test

### ISSUE THREAD

**Issue by SamedhG** [bdourdoufis/cs4500assignment1part2#15]
While the program will quit after running all the tests which will free any memory the Os gave it, I would much prefer if the test explicitly freed all memory that needs to be freed. This will also demonstrate the ownership rules of your API and is nice to have

**Comment by mwaldrich** [comment]
sure, working on this now

**Comment by mwaldrich** [comment]
fixed in 11538d3879086093817bf5481c46440c1da383e7
