### ISSUE TITLE
Make Queue methods virtual

### ISSUE THREAD

**Issue by tomharmon** [bdourdoufis/cs4500assignment1part2#16]
Could you please add the `virtual` keyword to Queue methods (enqueue, dequeue, peek) so that I can implement a StringQueue by overloading the Queue api? Based on piazza discussion and the assignment I think I have to implement something like that

**Comment by mwaldrich** [comment]
sure. fixed in 65d2cbdcee6394240314a0db6d11d98bc8ffd245.
