### ISSUE TITLE
Queue constructor

### ISSUE THREAD

**Issue by oriasm** [bdourdoufis/cs4500assignment1part2#19]
The Queue constructor that is supposed to copy the contents of the given Queue doesn't have any tests. Could yall either remove that constructor or add a test for it? I don't know if it makes a whole lot of sense to include it, given that we have a queue of objects. If you do keep it and add tests, how did you intended for objects to be copied?

For the sake of time, I'm perfectly okay if you just remove it :)

**Comment by mwaldrich** [comment]
ok, doing this now

**Comment by mwaldrich** [comment]
fixed in 1312c999067987b9e7390e0ef5a8c132d9359448
