### ISSUE TITLE
add_front should return a LinkedList*

### ISSUE THREAD

**Issue by SamedhG** [bdourdoufis/cs4500assignment1part2#2]
it would be nicer if add_front could return a linked list pointer otherwise the only possible implementation would be to move all elements it the linked list which will hinder performance.

**Comment by SamedhG** [comment]
Obviously this would also entail removing the `index` field as adding to front would require traversing and incrementing indices of everything in the list

**Comment by mwaldrich** [comment]
Our Queue class no longer has a dependency on a LinkedList, so you are now free to implement it however you want.
