### ISSUE TITLE
`index_of` signature conflicts with documentation

### ISSUE THREAD

**Issue by tomharmon** [bdourdoufis/cs4500assignment1part2#3]
The documentation of `index_of` states "Returns -1 if the object is not found in the list" but the signature says `index_of` returns a `size_t`, which is an unsigned type, meaning it can't be negative.

Can the signature of `index_of` please be changed to return an `int`?

**Comment by mwaldrich** [comment]
Our Queue class no longer has a dependency on a LinkedList, so you are now free to implement it however you want.
