### ISSUE TITLE
Enqueue/Dequeue + LinkedList conflicting documentation

### ISSUE THREAD

**Issue by tomharmon** [bdourdoufis/cs4500assignment1part2#4]
Enqueue documentation says "Add a new element to the back of the queue." but there are no `add_back` methods in linked list. While technically the `add_front` method can technically support this, it is counter-intuitive and clearer to do one of the two options:

There are two options:
1. Change `add_front` to `add_back`
2. Change `enqueue` documentation to "Add a new element to the front of the queue"

We would prefer the first option

**Comment by tomharmon** [comment]
Same issue with dequeue

**Comment by mwaldrich** [comment]
Our Queue class no longer has a dependency on a LinkedList, so you are now free to implement it however you want.
