### ISSUE TITLE
`remove_end` should return the `Object*` removed

### ISSUE THREAD

**Issue by tomharmon** [bdourdoufis/cs4500assignment1part2#5]
This simplifies the `dequeue` (not by much but its a little nicer and can be useful)

**Comment by tomharmon** [comment]
It should also be clarified that the caller of `remove_end` takes ownership of the element and therefore must delete the element removed after calling it. This allows for usage of `remove_end` in the `dequeue` method

**Comment by mwaldrich** [comment]
Our Queue class no longer has a dependency on a LinkedList, so you are now free to implement it however you want.
